[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Juan Bono <juanbono94@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
regex = "1"
serde ={ version = "1.0", features = ["derive"] }
serde_scan = "0.4.1"
